module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        page: "var(--color-page-bg)",
        surface: "var(--color-surface)",
        surfaceMuted: "var(--color-surface-muted)",
        text: "var(--color-text)",
        ink: "var(--color-text)",
        textSecondary: "var(--color-text-secondary)",
        muted: "var(--color-text-muted)",
        border: "var(--color-border)",
        borderSubtle: "var(--color-border-subtle)",
        accent: "var(--color-accent)",
        accentSoft: "var(--color-border-subtle)",
        accentForeground: "var(--color-accent-foreground)",
        confidenceLow: "var(--confidence-low)",
        confidenceMed: "var(--confidence-med)",
        confidenceHigh: "var(--confidence-high)",
        statusSuccess: "var(--status-success)",
        statusWarn: "var(--status-warn)",
        statusError: "var(--status-error)",
        critical: "var(--status-critical)",
        missing: "var(--status-missing)",
      },
      fontFamily: {
        display: ["\"Inter\"", "system-ui", "-apple-system", "\"Segoe UI\"", "Roboto", "sans-serif"],
        body: ["\"Inter\"", "system-ui", "-apple-system", "\"Segoe UI\"", "Roboto", "sans-serif"],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
      },
      borderRadius: {
        sm: "6px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
      },
      boxShadow: {
        subtle: "var(--shadow-subtle)",
      },
    },
  },
  plugins: [],
};
