export type GlobalSchemaField = {
  key: string;
  label: string;
  section: string;
  order: number;
  value_type: "string" | "number" | "boolean" | "date" | "unknown";
  repeatable: boolean;
  critical: boolean;
  optional: boolean;
};

export const GLOBAL_SCHEMA_SECTION_ORDER: string[] = [
  "Identificacion del caso",
  "Paciente",
  "Propietario",
  "Visita / episodio",
  "Clinico",
  "Costes / facturacion",
  "Metadatos / revision",
];

export const GLOBAL_SCHEMA_V0: GlobalSchemaField[] = [
  {
    key: "claim_id",
    label: "ID de reclamacion",
    section: "Identificacion del caso",
    order: 1,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "clinic_name",
    label: "Clinica",
    section: "Identificacion del caso",
    order: 2,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "clinic_address",
    label: "Direccion de la clinica",
    section: "Identificacion del caso",
    order: 3,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "clinical_record_number",
    label: "NHC / Historial clinico",
    section: "Identificacion del caso",
    order: 4,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "vet_name",
    label: "Veterinario",
    section: "Identificacion del caso",
    order: 5,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "document_date",
    label: "Fecha del documento",
    section: "Identificacion del caso",
    order: 6,
    value_type: "date",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "pet_name",
    label: "Nombre del paciente",
    section: "Paciente",
    order: 7,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "species",
    label: "Especie",
    section: "Paciente",
    order: 8,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "breed",
    label: "Raza",
    section: "Paciente",
    order: 9,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "sex",
    label: "Sexo",
    section: "Paciente",
    order: 10,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "age",
    label: "Edad",
    section: "Paciente",
    order: 11,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "dob",
    label: "Fecha de nacimiento",
    section: "Paciente",
    order: 12,
    value_type: "date",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "microchip_id",
    label: "Microchip",
    section: "Paciente",
    order: 13,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "weight",
    label: "Peso",
    section: "Paciente",
    order: 14,
    value_type: "string",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "coat_color",
    label: "Capa",
    section: "Paciente",
    order: 15,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "hair_length",
    label: "Pelo",
    section: "Paciente",
    order: 16,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "repro_status",
    label: "Estado reproductivo",
    section: "Paciente",
    order: 17,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "owner_name",
    label: "Nombre del propietario",
    section: "Propietario",
    order: 18,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "owner_address",
    label: "Direccion del propietario",
    section: "Propietario",
    order: 19,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "owner_id",
    label: "ID del propietario",
    section: "Propietario",
    order: 20,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "visit_date",
    label: "Fecha de visita",
    section: "Visita / episodio",
    order: 21,
    value_type: "date",
    repeatable: false,
    critical: true,
    optional: false,
  },
  {
    key: "admission_date",
    label: "Fecha de admision",
    section: "Visita / episodio",
    order: 22,
    value_type: "date",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "discharge_date",
    label: "Fecha de alta",
    section: "Visita / episodio",
    order: 23,
    value_type: "date",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "reason_for_visit",
    label: "Motivo de consulta",
    section: "Visita / episodio",
    order: 24,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "diagnosis",
    label: "Diagnostico",
    section: "Clinico",
    order: 25,
    value_type: "string",
    repeatable: true,
    critical: true,
    optional: false,
  },
  {
    key: "symptoms",
    label: "Sintomas",
    section: "Clinico",
    order: 26,
    value_type: "string",
    repeatable: true,
    critical: false,
    optional: false,
  },
  {
    key: "procedure",
    label: "Procedimiento",
    section: "Clinico",
    order: 27,
    value_type: "string",
    repeatable: true,
    critical: true,
    optional: false,
  },
  {
    key: "medication",
    label: "Medicacion",
    section: "Clinico",
    order: 28,
    value_type: "string",
    repeatable: true,
    critical: true,
    optional: false,
  },
  {
    key: "treatment_plan",
    label: "Plan de tratamiento",
    section: "Clinico",
    order: 29,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "allergies",
    label: "Alergias",
    section: "Clinico",
    order: 30,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "vaccinations",
    label: "Vacunaciones",
    section: "Clinico",
    order: 31,
    value_type: "string",
    repeatable: true,
    critical: false,
    optional: false,
  },
  {
    key: "lab_result",
    label: "Resultados de laboratorio",
    section: "Clinico",
    order: 32,
    value_type: "string",
    repeatable: true,
    critical: false,
    optional: false,
  },
  {
    key: "imaging",
    label: "Imagenes",
    section: "Clinico",
    order: 33,
    value_type: "string",
    repeatable: true,
    critical: false,
    optional: false,
  },
  {
    key: "invoice_total",
    label: "Total de factura",
    section: "Costes / facturacion",
    order: 34,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "covered_amount",
    label: "Importe cubierto",
    section: "Costes / facturacion",
    order: 35,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "non_covered_amount",
    label: "Importe no cubierto",
    section: "Costes / facturacion",
    order: 36,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
  {
    key: "line_item",
    label: "Linea de factura",
    section: "Costes / facturacion",
    order: 37,
    value_type: "string",
    repeatable: true,
    critical: false,
    optional: false,
  },
  {
    key: "notes",
    label: "Notas",
    section: "Metadatos / revision",
    order: 38,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: false,
  },
  {
    key: "language",
    label: "Idioma",
    section: "Metadatos / revision",
    order: 39,
    value_type: "string",
    repeatable: false,
    critical: false,
    optional: true,
  },
];
